services:
  server:
    build:
      context: .
    networks:
      - backend-network
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      JWT_SECRET: ${JWT_SECRET}
  mongodb:
    image: 'mongo:latest'
    networks:
      - backend-network
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_DATABASE=shopping'
    ports:
      - '27017:27017'
networks:
  backend-network:
    driver: bridge